physics_engine: 'physx'
env:
  numEnvs: 2
  numObservations: 52
  numActions: 2
  maxEpisodeLength: 30
  clipActions: 1
sim:
  use_gpu_pipeline: True
  up_axis: 'z'
  dt: 0.05
  gravity: [0.0, 0.0, -9.81]